name: 'Claim Access Rights'
description: 'Allows users to claim granular access rights (view, edit) on listings and content, featuring configurable Exclusive, Replace, and Append modes, automated approval via ECA, and access expiry.'
type: recipe
install:
  - webform
  - webform_ui
  - eca
  - eca_base
  - eca_content
  - eca_ui
  - bpmn_io
  - claim_access_rights
config:
  strict:
    - claim_access_rights.settings
    - webform.webform.claim_listing
    - eca.eca.claim_access_auto_approval
  actions:
    user.role.authenticated:
      grantPermissions:
        - 'claim access rights'
